export const categoryDictionary = {
  'Frontend Development': [
    'typescript',
    'javascript',
    'react.js',
    'next.js',
    'angular',
    'redux',
    'redux-saga',
    'redux-thunk',
    'rtk query',
    'react-query',
    'html',
    'css',
    'scss',
    'sass',
    'mui',
    'ngrx',
    'rxjs',
    'babel',
    'bootstrap',
    'tailwind',
    'pwa',
    'spa',
    'a11y',
    'graphql',
    'ecmascript',
    'web',
    'webpack',
    'state management',
    'frontend',
  ],
  'Mobile Development': ['react-native', 'react native', 'mobile development', 'xamarin'],
  'Backend Development': [
    'node.js',
    'nest.js',
    'express.js',
    'nestjs',
    'websocket',
    'serverless',
    'authentication',
    'authorization',
    'graphql',
    'backend',
    'microservice',
  ],
  '.NET Development': [
    'razor pages',
    'asp.net mvc',
    'asp.net core',
    'asp.net web api',
    'asp.net',
    'c#',
    '.net',
    '.net core',
    '.net framework',
    'entity framework core',
    'ef core',
    'linq',
    'blazor',
    'signalr',
    'solid',
    'authentication',
    'authorization',
    'microservice',
    'backend',
  ],
  Testing: [
    'jest',
    'xunit',
    'jasmine',
    'react-testing-library',
    'swagger',
    'code coverage',
    'postman',
    'mocha',
    'tdd',
    'test-driven development',
    'e2e',
    'bdd',
    'behavior-driven development',
    'cypress',
    'testing',
  ],
  Databases: [
    'postgresql',
    'mongodb',
    'typeorm',
    'mongoose',
    'redis',
    'sql',
    't-sql',
    'nosql',
    'cosmosdb',
    'acid',
    'cap theorem',
    'cap',
    'orm',
    'prisma',
    'migrations',
    'database normalization',
    'indexing strategies',
    'database optimization',
    'database',
  ],
  Technologies: [
    'rest',
    'restful',
    'protocol',
    'rabbit',
    'rabbitmq',
    'tcp',
    'upd',
    'grpc',
    'rpc',
    'http',
    'https',
    'oauth',
    'openapi',
    'gateway',
    'webhooks',
    'graphql',
    'architecture',
    'api',
    'service',
  ],
  'Utilities and Tools': [
    'npm',
    'docker',
    'devops',
    'vcs',
    'cd',
    'ci',
    'jenkins',
    'travis',
    'iac',
    'kubernetes',
    'nuget',
    'debugging',
    'ci/cd',
    'git',
    'github',
    'jwt',
    'prettier',
    'utilities',
    'tools',
  ],
};
